[REL] project_description to V11.
ingadhoc/project pull request #63
Opened 2018-06-15 11:22 UTC by ValentinoDefelice

[ADD] Models folder.
[FIX] Rename fields.
[FIX] Update README.
[FIX] Minor fix.

2018-06-15 16:14 UTC, nicomacr requested changes
Hi @ValentinoDefelice  thanks for the PR:
I put some comments below.

2018-06-15 16:14 UTC, nicomacr commented on project_description/models/account_analytic_account.py
[Here](https://github.com/adhoc-dev/project/blob/7a30b818804954783bc2495d82582e3a5f0773b5/project_description/models/account_analytic_account.py#L8) the name of the model should be using the Camecase convencion

2018-06-15 16:14 UTC, nicomacr commented on project_description/views/project_project_views.xml
> +        <field name="name">project_tags.project.form</field>
The `name` should be `project.project.form.inherit`

2018-06-15 16:14 UTC, nicomacr commented on project_description/views/project_project_views.xml
> +    <record id="view_project_tags_project_form" model="ir.ui.view">
The `id` should be `edit_project`

2018-06-15 18:10 UTC, zaoral requested changes
Hi @ValentinoDefelice 

Here are the results of the technical review you ask. Leave you some comments here.

About the functional review LGTM+1

2018-06-15 18:10 UTC, zaoral commented on project_description/README.rst
> -To install this module, you need to:
This sections are empty, will be good if they have content as it is in the README guideline template.
Would be good if could look like the next one:

![image](https://user-images.githubusercontent.com/7593953/41478402-eb611cda-709d-11e8-8c6e-907118962a54.png)

2018-06-15 18:10 UTC, zaoral commented on project_description/__init__.py
> +from . import models
this file is marked as executable file and it should not.
Please remove the execute permissions with "chmod -x file_name"

Please this also apply to the next files

```
models/__init__.py
i18n/project_description.pot
views project_project_views.xml
```

2018-06-15 18:10 UTC, zaoral commented on project_description/models/account_analytic_account.py
>          help="Account analytic account description"
>          help="Account analytic account description"

add `,` at the end of the line

>         help="Account analytic account description",

I think we could change the help attribute to "Description of the project"

2018-06-15 18:10 UTC, zaoral commented on project_description/README.rst
>  Adds account_analytic_account description field on project form view.
This seems to be a technical premise.
Please add a more functional description, could be something like

"Be able to set a Description to Projects in order to extend information about the project meaning"

2018-06-15 18:13 UTC, zaoral commented
Last but not less, your PR is out-of-date with the base branch, please do a rebase to the 11.0 branch of your branch after apply the new suggested changes.

Best Regards

2018-06-18 14:30 UTC, nicomacr submitted a review, later dismissed

2018-06-18 14:49 UTC, zaoral submitted a review, later dismissed

2018-06-19 18:34 UTC, nicomacr approved these changes

2018-06-20 12:09 UTC, merged