[REL] Migration project_usability rename project_ux to 11.0
ingadhoc/project pull request #64
Opened 2018-06-15 16:05 UTC by nicomacr

2018-06-15 18:50 UTC, zaoral requested changes
Hi @nicomacr 

Thanks for this PR.
I have some comments after the review please review them.

I only made a technical review no funcional review.

Also, now the module has been renamed the i18n files are not valid since they mention to another inexistente module, please delete then and create a new es.po file for this module.

Best Regards

2018-06-15 18:50 UTC, zaoral commented on project_ux/views/project_project_views.xml
> +<?xml version="1.0"?>
both view files are marked as executable files, please run a chmox -x file in order to fix it

2018-06-15 18:50 UTC, zaoral commented on project_ux/README.rst
> +Installation
This sections are empty, will be good if they have content as it is in the README guideline template.
Would be good if could look like the next one:

![image](https://user-images.githubusercontent.com/7593953/41478402-eb611cda-709d-11e8-8c6e-907118962a54.png)

2018-06-15 18:50 UTC, zaoral commented on project_ux/models/project_task.py
>          if self.template_task_id:
use early return approach to reduce complexity of the code

```python
if not self.template_task_id:
   return

data = self.template_task_id.copy_data()
for k, v in data[0].items():
```

2018-06-15 18:50 UTC, zaoral commented on project_ux/views/project_project_views.xml
> +        <field name="name">Tasks</field>
I am not sure, but by the id of this action its seems like the name should be Sub Tasks, instead of Tasks

2018-06-15 18:50 UTC, zaoral commented on project_ux/views/project_project_views.xml
> +        <field name="name">Tasks</field>
Also seems to be that this action and the one before  `project.act_project_project_2_project_task_all` are related to `res_model = project.task` so I think they should go into the `project_task_views.xml` file

2018-06-15 18:50 UTC, zaoral commented on project_ux/views/project_task_views.xml
> +    <record id="project.act_project_project_2_project_task_all" model="ir.actions.act_window">
This action is repeated, is in both `project_project_views.xml` and `project_task_views.xml`

2018-06-18 12:13 UTC, nicomacr commented
@zaoral I've made the suggested modifications.

2018-06-18 17:49 UTC, zaoral requested changes
Hi @nicomacr 

Thank you for the changes.

The translation files are referring to deprecated product_usability module. Please delete this files and generate a new one es.po for the new product_ux module

2018-06-18 20:56 UTC, zaoral approved these changes

2018-06-19 10:12 UTC, merged